-- 0001_telemetry: anonymous playtest telemetry (POC-5). One row per event
-- the web client reports: a resolved round (what was telegraphed, what
-- was cast, how the player reacted, who scored, how long the commit
-- took), a rematch, or a match end. No account, no IP, no user agent:
-- session_id is a random UUID the client keeps in local storage so one
-- device's rounds can be grouped. Integers only (epoch-ms); UUID text
-- keys, generated by the worker.
CREATE TABLE telemetry_events (
  id                TEXT    PRIMARY KEY,
  ts                INTEGER NOT NULL,
  event             TEXT    NOT NULL CHECK (event IN ('round', 'rematch', 'match_end')),
  session_id        TEXT    NOT NULL,
  match_seed        TEXT    NOT NULL,
  round             INTEGER NOT NULL,
  scenario_id       TEXT,
  telegraph_preset  TEXT    CHECK (telegraph_preset IN ('high', 'medium')),
  telegraph         TEXT,
  opponent_spell    TEXT,
  player_spell      TEXT,
  player_reaction   TEXT    CHECK (player_reaction IN ('null', 'reflect', 'silence')),
  opponent_reaction TEXT    CHECK (opponent_reaction IN ('null', 'reflect', 'silence')),
  player_seals      INTEGER NOT NULL,
  opponent_seals    INTEGER NOT NULL,
  player_gained     INTEGER NOT NULL DEFAULT 0,
  opponent_gained   INTEGER NOT NULL DEFAULT 0,
  time_to_commit_ms INTEGER,
  web_version       TEXT    NOT NULL
);
CREATE INDEX telemetry_events_session_ts ON telemetry_events (session_id, ts);
CREATE INDEX telemetry_events_scenario ON telemetry_events (event, scenario_id);
